create table Person(
                       id int primary key generated by default as identity ,
                       username varchar (100) not null ,
                       year_of_birth int not null ,
                       password varchar not null
);

insert into Person (username, year_of_birth, password) VALUES ('Margarita', 1981, 'margo');
insert into Person (username, year_of_birth, password) VALUES ('Miron', 2019, 'miron');
insert into Person (username, year_of_birth, password) VALUES ('Alena', 2020, 'alena');